### ISSUE TITLE
Create new column

### ISSUE THREAD

**Issue by nanthony007** [jlumbroso/comma#4]
Hi!  First issue.  I love your package and prefer its simplicity when doing simple `csv` work much more than pandas and all of its dependencies.  The one major behavior missing in my use case is the ability to create new columns easily.  So I would like to discuss adding this feature and working on it.

I think this would require a feature similar to `pandas.Series` or `gota.Series` ([gota](https://github.com/go-gota/gota)).

I have thought of two options:
1.  Using a dictionary with one key (the column header name) and a list of values for the column
2. Using a list of dictionaries, each with one key and value.

The first option could add the key (column) into `table.header` and then simply add the values (something akin to `table['col'] = [<list of vals>]`

The second option could add the column header then simply loop through the table and the new column values and union the dictionaries.

Please let me know what you think, and thank you for your amazing project!

**Comment by jlumbroso** [comment]
I am so sorry @nanthony007 for missing your fantastic first issue — as you can tell, this is my first real open source project, and I wasn't expecting anybody to take a shining to this library. Thank you so much! 🙏🏻

I just stumbled on this, and I am going to noodle a little bit on it, but [I also saw you forked the repo](https://github.com/nanthony007/comma) and I was wondering if you had experimented on your own. I know this was about a year ago, and I am so sorry, but I am excited to look into this if it's still of interest to you. 😊

**Comment by nanthony007** [comment]
Hi @jlumbroso, glad to connect!

I haven't used the package in a while and just looking back through I was wondering if something like `table['new_col'] = [12, 15, 16]` would work?  I see in your examples you use that syntax to _change_ a column's values but I don't think it holds for new columns...


If the above. does not work I think the easiest solution would be to add a new method that takes a dictionary of type `[str, list[Any]]` and appends that to `CommaTable` as a new column by performing any necessary operations on it.

So the new API would look like:
```python
new_data = {"age": [12, 15, 16]}
table.insert(new_data)
```


Glad to be connecting 😃
